[project]
name = "data-dallion-framework"
version = "1.0.8rc1"
description = "DataDallion Framework is a comprehensive metadata-driven data engineering framework for building and orchestrating Medallion Architecture data pipelines (Bronze -> Silver -> Gold layers). It provides an end-to-end solution for data ingestion, standardization, quality management, and transformation with support for multiple data sources and automated orchestration."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.42.76",
    "jinja2>=3.1.6",
    "jsonpath-ng>=1.8.0",
    "jwt>=1.4.0",
    "niquests>=3.18.2",
    "paramiko>=4.0.0",
    "polars>=1.39.3",
    "pydantic-settings>=2.13.1",
    "sqlmodel>=0.0.37",
]

[project.scripts]
data-dallion-framework = "data_dallion_framework:main"

[project.optional-dependencies]
extras = [
    "pyspark>=4.1.1",
    "delta-spark"
]
sql-backend = [
    "mariadb>=1.1.14",
]

[build-system]
requires = ["uv_build>=0.8.4,<0.9.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipykernel>=7.2.0",
]
